/*     */ package net.minecraft.util.parsing.packrat;
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ class Silent
/*     */   extends Object
/*     */   implements ParseState<S>
/*     */ {
/* 186 */   private final ErrorCollector<S> silentCollector = new ErrorCollector.Nop();
/*     */ 
/*     */ 
/*     */   
/* 190 */   public ErrorCollector<S> errorCollector() { return this.silentCollector; }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/* 195 */   public Scope scope() { return CachedParseState.this.scope(); }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/* 200 */   public <T> T parse(NamedRule<S, T> rule) { return (T)CachedParseState.this.parse(rule); }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/* 205 */   public S input() { return (S)CachedParseState.this.input(); }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/* 210 */   public int mark() { return CachedParseState.this.mark(); }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/* 215 */   public void restore(int mark) { CachedParseState.this.restore(mark); }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/* 220 */   public Control acquireControl() { return CachedParseState.this.acquireControl(); }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/* 225 */   public void releaseControl() { CachedParseState.this.releaseControl(); }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/* 230 */   public ParseState<S> silent() { return this; }
/*     */ }


/* Location:              C:\Users\Curse\Desktop\servers\test\versions\1.21.11_unobfuscated\server-1.21.11_unobfuscated.jar!\net\minecraf\\util\parsing\packrat\CachedParseState$Silent.class
 * Java compiler version: 21 (65.0)
 * JD-Core Version:       1.0.7
 */